// Seed script for development database
import prisma from '../connection.js';

async function seed() {
  console.log('Seeding database...');

  // Create default admin user
  const admin = await prisma.user.upsert({
    where: { email: 'admin@example.com' },
    update: {},
    create: {
      email: 'admin@example.com',
      name: 'Admin',
      password: '$2a$12$LJ3m4ys3Lk0TSwHkOZqYWOqKJZxH5YHK7qZHK7qZHK7qZHK7qZHK', // password: admin123
      role: 'admin'
    }
  });
  console.log('Created admin user:', admin.email);

  // Create a sample project
  const project = await prisma.project.upsert({
    where: { id: 1 },
    update: {},
    create: {
      name: 'Sample Project',
      description: 'A sample project generated by Agent Tree System'
    }
  });
  console.log('Created sample project:', project.name);

  console.log('Seed completed!');
}

seed()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
